### ISSUE TITLE
数据集文件都被作者清除了

### ISSUE THREAD

**Issue by cocollschool** [zhenglab/PlanktonMKL#1]
code里的训练集、测试集；dataset里的三个类别下，所有的图像文件都没了

这个项目估计也没人来看了

**Comment by zhenghaiyong** [comment]
你好，数据集可以自行找数据集作者的网站下载，未经原始数据集作者同意我们不能放在这里发布，谢谢。

**Comment by zhenghaiyong** [comment]
> code里的训练集、测试集；dataset里的三个类别下，所有的图像文件都没了
> 
> 这个项目估计也没人来看了
